services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - "5000"
    networks:
      custom_network:
        ipv4_address: 172.20.0.2

  nginx:
    image: nginx:latest
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
    networks:
      custom_network:
        ipv4_address: 172.20.0.3

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16