FROM python:3.13-slim

WORKDIR /app

COPY api/app.py /app
COPY api/templates /app/templates

RUN pip install Flask
RUN apt update && apt install -y iputils-ping dnsutils

EXPOSE 5000

CMD ["python", "app.py"]
