services:
  python_server:
    image: python:3.13-slim
    volumes:
      - .:/app
    working_dir: /app
    command: python server.py
    ports:
      - "8080:8080"

  busybox_client:
    image: busybox:latest
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity
    depends_on:
      - python_server