services:
  python_server:
    image: python:3.13-slim
    volumes:
      - .:/app
    working_dir: /app
    command: python server.py
    ports:
      - "1337:1337"

  python_client:
    image: python:3.13-slim
    volumes:
      - .:/app
    working_dir: /app
    command: python client.py
    depends_on:
      - python_server